import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/modules/common/widgets/header";
import { Locale } from "@/i18n-config";
import useAppData from "@hooks/useAppData";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  children: React.ReactNode;
  params: { lang: Locale };
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { lang } }: Props) {
  useAppData.setState({ locale: lang });

  return (
    <html lang="en">
      <body className={`${inter.className} bg-dark text-white`}>
        <Header />
        <main className="container mt-28">{children}</main>
      </body>
    </html>
  );
}
